services:
  - type: web
    name: gateway-checker-bot
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python gateway_checker_bot.py"
    envVars:
      - key: TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
